### ISSUE TITLE
When Build and deploy

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/cloudbeaver#1150]
![image](https://user-images.githubusercontent.com/43168824/190105666-8e9b5769-b9d7-46c4-9c8c-c287d1299840.png)
![image](https://user-images.githubusercontent.com/43168824/190105735-b5bb2e86-a815-4df3-882b-880c0f8ab933.png)
It has some problem.I follow the wiki . And java is 11

**Comment by kseniaguzeeva** [comment]
Unfortunately, I need more details and steps to reproduce in order to help you to solve your issue.
Could you please try to find out the answer in similar tickets:

[Error in all packages in following folders to deploy cloudbeaver in eclipse java](https://github.com/dbeaver/cloudbeaver/issues/988)
[After importing the project in eclipse, debug reports an error](https://github.com/dbeaver/cloudbeaver/issues/947#top)(https://github.com/dbeaver/cloudbeaver/issues/947)
[not nunning in eclipse](https://github.com/dbeaver/cloudbeaver/issues/630)

**Comment by ccczhouxin** [comment]
I clone the project and follow https://github.com/dbeaver/cloudbeaver/wiki/Build-and-deploy.
until third step is ok 
![image](https://user-images.githubusercontent.com/43168824/190116174-dab4528a-6462-4277-87df-6eb062569439.png)
when i input ./run-server.sh it said :
![image](https://user-images.githubusercontent.com/43168824/190116440-b9412bfc-4b45-4450-bd37-cfb430154dc9.png)
![image](https://user-images.githubusercontent.com/43168824/190116681-7c8cbca3-888f-49d5-8186-e32ec14931ba.png)

**Comment by kseniaguzeeva** [comment]
Could you please also send logs completely?

**Comment by ccczhouxin** [comment]
I use terminal to do.The result is the small picture,i don know other logs.
