### ISSUE TITLE
Error while editing user roles

### ISSUE THREAD

**Issue by E1izabeth** [dbeaver/cloudbeaver#1171]
**Describe the bug**

I can't save user roles if I check and then uncheck one of the checkboxes without save.

**To Reproduce**
1. Start editing user roles
2. Check 3 checkboxes
3. Uncheck one of them
4. Press Save button
4. See error "Error revoking role: User 'user13' doesn't have role '4'"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 22.2.1

**Comment by miltonchirinos44** [comment]
A query @E1izabeth , I am new to cloudbeaver development a query which version of cloudbeaver is using the `community `or `enterprice` version since I don't have these options in my cloudbeaver community
![image](https://user-images.githubusercontent.com/52106718/191335548-24d279eb-c0fd-4260-a55c-10b1713cdb93.png)
