### ISSUE TITLE
Some questions about the webapp folder

### ISSUE THREAD

**Issue by Ezreal09** [dbeaver/cloudbeaver#154]
Hello, can I run the front end using only the webapp folder？
I followed the steps in the readme.md file in the webapp directory and executed ‘npx serve packages/product-default/lib’. The project ran on localhost:5000, but it was 404 when I visited.
Looking forward to your reply，thanks

**Comment by Wroud** [comment]
Hello, if you want to run frontend in development mode, I recommend to use [this instruction](https://github.com/dbeaver/cloudbeaver/wiki/Frontend-description#development).
I'm added a build step to the readme, but running frontend separately from the backend has no sense, because the app won't load (it's will be sending requests to localhost:5000/dbeaver backend)
