### ISSUE TITLE
Server configuration and other settings lost after reboot

### ISSUE THREAD

**Issue by andrieskrause** [dbeaver/cloudbeaver#2182]
**Describe the bug**
After the docker container is started for the first time, the web UI will take you to the INITIAL SERVER CONFIGURATION setup page. Upon saving these configuration settings the admin user can setup connections and user access. All these settings are lost after a restart and the user will be directed to the INITIAL SERVER CONFIGURATION page again. The issue pertains to running Cloudbeaver in Mac OS (M1) using Docker Desktop.

**To Reproduce**
1. docker pull dbeaver/cloudbeaver:latest
2. docker run --name cloudbeaver -p 8080:8978 -v /var/cloudbeaver/workspace:/opt/cloudbeaver/workspace -d dbeaver/cloudbeaver:latest
3. Go to http://localhost:8080/#/ in browser which will redirect to http://localhost:8080/#/setup/welcome
4. Setup server configuration, connections, users and access.
5. Stop container and reboot system
6. After reboot restart the container
7. Go to http://localhost:8080/#/ again and the previous setup is lost; it will redirect again to http://localhost:8080/#/setup/welcome where you have to start all over with the setup.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.1.1 (Apple M1 Pro)
 - Browser: Chrome Version 119.0.6045.159 (Official Build) (arm64)
 - Cloudbeaver Version: 23.2.5

**Comment by EvgeniaBzzz** [comment]
Hi @andrieskrause!
Docker does not have access to /var/cloudbeaver/workspace in your case. You can use another directory on your computer by specifying the path to the directory instead of `{{selected_path}}`: 
`docker run --name cloudbeaver -p 8080:8978 -v {{selected_path}}/cloudbeaver/workspace:/opt/cloudbeaver/workspace -d dbeaver/cloudbeaver:latest`
Or use the command when Docker decides on its own where to store persisting data:
`docker run --name cloudbeaver -p 8080:8978 -v /opt/cloudbeaver/workspace -d dbeaver/cloudbeaver:latest`

**Comment by andrieskrause** [comment]
It did resolve the issue. Thanks.

**Comment by EvgeniaBzzz** [comment]
Thank you for being with CloudBeaver!
