### ISSUE TITLE
MSSQL Connection/Driver Support and Version Upgrade

### ISSUE THREAD

**Issue by gitquestt** [dbeaver/cloudbeaver#256]
Hello,

I have been using Cloudbeaver for 3 months in a docker container. It is probably version 1.2.0.
I need to connect to the MSSQL database, but you mentioned that issue #220 will be available in version 1.3

My first question, how can I upgrade the Cloudbeaver without deleting my existing connections/users? I haven't seen a document about doing this, especially in use with containers. 

My second question, is there a manual way to connect to the MSSQL database right now, or does Cloudbeaver not fully support it?

Thanks.

**Comment by serge-rider** [comment]
SQL Server support will be added in #220

Docker version keeps all configuration in /var/cloudbeaver folder. 
If you just upgrade docker image version then all configuration will be kept. 

Otherwise you can just copy configuration from the old version (folder workspace/GlobalConfiguration) to /var/cloudbeaver.
