### ISSUE TITLE
DB connections in management database tables instead json files

### ISSUE THREAD

**Issue by rlauti1980** [dbeaver/cloudbeaver#2700]
When dealing with a lot of databases (in our case more than 1500), it would be easier, if the database connections would be stored in the management database of cloudbeaver, instead of json files. 
We want to create/configure connections for all databases. For sure no one wants to do this for every single db using the UI. Dealing with json files is a lot better, but also not that great.
When the connections would be stored in the db, we would be able to use sql statements to create/configure the connections. Also the whole configuration would be backed up with the backup of the CB management database.

Is there a chance this could be implemented?

Thanks!
René

**Comment by EvgeniaBzzz** [comment]
Hi @rlauti1980,

The probability of implementation is very low because of version and product compatibility issues. However, we are thinking about how to make the work easier.

What is your main difficulty? How exactly do you use CloudBeaver? Are all the 1500 connections different? It would be helpful to understand your use cases.

As a workaround, you can try using multiple JSON files. CloudBeaver can load multiple connection files. Any files in the project folder matching the `.dbeaver/data-sources*.json` pattern will be loaded on startup. So, you can create a file, for example, `.dbeaver/data-sources-2.json` in the project folder, and CloudBeaver will see it.

**Comment by rlauti1980** [comment]
Hi EvgeniaBzzz,

thank you for your fast response. Yes, all connections are different. Different hosts, different service names. But they're all Oracle databases.
We have a table in a management database, with the connection informations of all other databases. So we have to export these somehow, to the correct json format, so we're able to import them in the container and use them in CB.
We're still figuring out, what the best way is to do it.

It's a good hint, that it's possible to use several json files. It creates a better overview and some logical differentiation, if needed.

Thank you so far!

**Comment by rlauti1980** [comment]
In the json file the Oracle connections start with a kind of unique identifier. How can i create this when i add a new connection on the json level? Or can i leave it blank?

e.g. "oracle_thin-**18e1915a5c3-794f00ff005810aa**": {
                    "provider": "oracle",
                    "driver": "oracle_thin",

**Comment by EvgeniaBzzz** [comment]
Thanks for your update!

You can use _any_ unique identifier for a new connection. 
e.g. `precious-oracle-1`

**Comment by EvgeniaBzzz** [comment]
Hi @rlauti1980 
Have you tried using multiple files? Does it work for your case?

**Comment by rlauti1980** [comment]
Hi EvgeniaBzzz,

yes it does work.

Thank you!

**Comment by EvgeniaBzzz** [comment]
Great!
I'm closing this issue as we are  not going to store connections in database.
But we'll keep in mind your case and think about other solution.
