### ISSUE TITLE
Connection missing and checkbox

### ISSUE THREAD

**Issue by dinu111** [dbeaver/cloudbeaver#2855]
I have upgraded to cloudBeaver 24.1.5 and with the upgrade I am not able to see any new connections i create in the "Connection Template" tab.
As you can see in the screenshots bellow, I have a connection created but its not visible in the left side pannel.
![image](https://github.com/user-attachments/assets/a032c55e-a529-41b1-a957-e85c010811da)
![image](https://github.com/user-attachments/assets/483ebedf-0095-4641-958e-8042b3c95248)

Also the in the marked red area it used to be a checkbox with the "save credentials" but its missing right now
![image](https://github.com/user-attachments/assets/cd7295b6-34af-4124-bd53-4a23acfa6d48)

Am I miss using the new config or what could be wrong here? 
Any help is appreciated, thank you.

**Comment by EvgeniaBzzz** [comment]
Hi @dinu111 
Up to version 23.2.0, the Connection Templates tab included both templates and existing connections. After this version, the tab only contains templates for connections (that are created on the same tab of admin panel). 
Navigate to main page - Connections - From a template to reuse your created template.
It is not allowed to save credentials in a template, that's why there is no check-box.
![image](https://github.com/user-attachments/assets/13ce2218-ac06-45bf-8110-1b4334d0caba)

You can see all your existing connections in the navigator on the main page of the application. You still can change any settings here.
![image](https://github.com/user-attachments/assets/ab26b378-b51a-4c84-9c15-66deeefcf81d)

**Comment by dinu111** [comment]
@EvgeniaBzzz I see, thank you for the fast response, I have 1 more question if its not too much asking, the reversProxy functionality used to work by just toggling the Revers Proxy toggle
![image](https://github.com/user-attachments/assets/95b8be6f-4d54-4850-90a9-ffd992a00131)

But now I have to go in the .cloudbeaver.runtime.conf and setting it here to true
![image](https://github.com/user-attachments/assets/42885d2f-2350-4d6f-9997-f21264626e70)

Any idea why that is happening?

**Comment by EvgeniaBzzz** [comment]
It works as expected. These settings are not directly related to each other.
[enableReverseProxyAuth](https://github.com/dbeaver/cloudbeaver/wiki/Reverse-proxy-header-authentication) is needed for user authentication in CloudBeaver
[serverProxy](https://github.com/dbeaver/cloudbeaver/wiki/Server-configuration#application-parameters) is needed when CB is behind nginx or another web server

**Comment by dinu111** [comment]
@EvgeniaBzzz Indeed we use CB behind an nginx so i guess moving forward i will have to modify the .cloudbeaver.runtime.conf
Thank you for your fast responses, much appreciated. This thread can be closed from my point of view.

**Comment by EvgeniaBzzz** [comment]
Yes, you'll have to modify it manually in the config, as you are a real pro user 😉
Any questions and suggestions are welcome!
Thank you for being with CloudBeaver 🦫
