### ISSUE TITLE
Is there any Docker image with all database drivers?

### ISSUE THREAD

**Issue by suhasadhav** [dbeaver/cloudbeaver#301]
Hi,
I just started using cloudbeaver but I need some more drivers like Hive, Greenplum, Cassandra. Do anyone has prebuilt docker image with all drivers?

As building source seems complicated, I have gone through all the documentation for adding new drivers.

**Comment by kseniiaguzeeva** [comment]
Hi,
please try to use this instruction for Greenplum https://github.com/dbeaver/cloudbeaver/wiki/Driver-managements.
Hive and Cassandra will be added to Enterprise version later

**Comment by suhasadhav** [comment]
Is it possible to add Hive, Impala and Cassandra as well?

**Comment by serge-rider** [comment]
@suhasadhav It is possible to add Hive (following the instructions above). Although Hive JDBC driver is huge and includes entire Hadoop infrastructure. We don't include it in community docker image because it will double docker image size.

DBeaver Cassandra driver isn't open-source, it can't be included in community version of CloudBeaver.

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen the ticket if you have any questions.
