### ISSUE TITLE
Oauth/OIDC Support

### ISSUE THREAD

**Issue by HumairAK** [dbeaver/cloudbeaver#443]
**Is your feature request related to a problem? Please describe.**
I noticed that there is no support for enabling auth via oauth/OIDC, are there plans to add this? 

**Describe the solution you'd like**
Oauth/OIDC support for authentication/authorization with the ability to map userinfo to roles.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. We will add it in EE version, but I don't know exact date for now.

**Comment by TatyanaSsau** [comment]
We added support of OAuth/OpenID for Enterprice Edition. 
You can try it for free with trial https://cloudbeaver.io/trial/

**Comment by redtux** [comment]
Hi @kseniiaguzeeva and @TatyanaSsau, thank you for this great project and for the good work!

While LDAP support seems to be still missing (in both EE & CE), it's good to know that you succeeded in implementing OIDC support. I'm late to the party, but are there any plans to add this to the CE version?

> Note: This feature is available in [Enterprise](https://github.com/dbeaver/cloudbeaver/wiki/CloudBeaver-EE-Overview), [AWS](https://github.com/dbeaver/cloudbeaver/wiki/AWS-Overview) and [Team](https://github.com/dbeaver/cloudbeaver/wiki/Getting-started-with-Team-Edition) editions only.

See: https://github.com/dbeaver/cloudbeaver/wiki/OpenID

The description of this repo says "CloudBeaver Community" and "Cloud Database Manager - Community Edition", so to my understanding this issue maybe should be reopened (if planned/undecided), or at least it should be closed as rejected instead of completed (if discarded/not planned for CE for some reason).

Please bear in mind that closing this issue as completed while not having implemented the code in the repo might be confusing or misleading, as the EE version seems to be a different piece of software.

Is EE code using a proprietary license, or is it also subject to the Apache License 2.0 just as CloudBeaver CE? If so (and if CE and EE were fully compatible), the described feature probably could be incorporated into this repo without much effort, right?

**Comment by Linkk2000** [comment]
As a user of the Community Edition, I’d love to see this feature included! It would add significant value for self-hosted setups. Please consider making it available in the open-source version. Thanks for your work!
